//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiPugPigConnector.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPiPugPigConnector.Tests.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;feed xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:opds=&quot;http://opds-spec.org/2010/catalog&quot;&gt;
        ///  &lt;id&gt;com.mycompany.myeditions&lt;/id&gt;
        ///  &lt;link rel=&quot;self&quot; type=&quot;application/atom+xml;profile=opds-catalog;kind=acquisition&quot; href=&quot;http://epipugpigdemo.azurewebsites.net/editions.xml&quot;/&gt;
        ///  &lt;title&gt;All Editions&lt;/title&gt;
        ///  &lt;updated&gt;2011-08-08T15:02:28+00:00&lt;/updated&gt;
        ///  &lt;author&gt;
        ///    &lt;name&gt;Nansen&lt;/name&gt;
        ///  &lt;/author&gt;
        ///&lt;/feed&gt;.
        /// </summary>
        internal static string editionsNoEntriesTestXml {
            get {
                return ResourceManager.GetString("editionsNoEntriesTestXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;feed xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:opds=&quot;http://opds-spec.org/2010/catalog&quot;&gt;
        ///  &lt;id&gt;com.mycompany.myeditions&lt;/id&gt;
        ///  &lt;link rel=&quot;self&quot; type=&quot;application/atom+xml;profile=opds-catalog;kind=acquisition&quot; href=&quot;http://epipugpigdemo.azurewebsites.net/editions.xml&quot;/&gt;
        ///  &lt;title&gt;All Editions&lt;/title&gt;
        ///  &lt;updated&gt;2011-08-08T15:02:28+00:00&lt;/updated&gt;
        ///  &lt;author&gt;
        ///    &lt;name&gt;Nansen&lt;/name&gt;
        ///  &lt;/author&gt;
        ///  &lt;entry&gt;
        ///    &lt;title&gt;Paned template&lt;/title&gt;
        ///    &lt;id&gt;012356789&lt;/i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string editionsTestXml {
            get {
                return ResourceManager.GetString("editionsTestXml", resourceCulture);
            }
        }
    }
}
