//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiPugPigConnector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPiPugPigConnector.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;feed xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:opds=&quot;http://opds-spec.org/2010/catalog&quot;&gt;
        ///  &lt;id&gt;&lt;/id&gt;
        ///  &lt;link rel=&quot;self&quot; type=&quot;application/atom+xml;profile=opds-catalog;kind=acquisition&quot; href=&quot;&quot;/&gt;
        ///  &lt;title&gt;&lt;/title&gt;
        ///  &lt;updated&gt;&lt;/updated&gt;
        ///  &lt;author&gt;
        ///    &lt;name&gt;&lt;/name&gt;
        ///  &lt;/author&gt;
        ///&lt;/feed&gt;.
        /// </summary>
        public static string editionsEntryTemplateXml {
            get {
                return ResourceManager.GetString("editionsEntryTemplateXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;feed xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:opds=&quot;http://opds-spec.org/2010/catalog&quot;&gt;
        ///  &lt;id&gt;&lt;/id&gt;
        ///  &lt;link rel=&quot;self&quot; type=&quot;application/atom+xml;profile=opds-catalog;kind=acquisition&quot; href=&quot;&quot;/&gt;
        ///  &lt;title&gt;&lt;/title&gt;
        ///  &lt;updated&gt;&lt;/updated&gt;
        ///  &lt;author&gt;
        ///    &lt;name&gt;&lt;/name&gt;
        ///  &lt;/author&gt;
        ///&lt;/feed&gt;.
        /// </summary>
        public static string editionsRootTemplateXml {
            get {
                return ResourceManager.GetString("editionsRootTemplateXml", resourceCulture);
            }
        }
    }
}
